[package]
name = "neatproto-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
convert_case = { workspace = true }
clap = { version = "4.5.38", features = ["derive"] }
neatproto-analysis = { path = "../analysis" }
neatproto-ast = { path = "../ast" }
